sudo: required
language: python
python:
  - "3.4"
env:
  - database_server=$database_server database_name=$database_name database_password=$database_password database_username=$database_username database_tenantpw=$database_tenantpw
services:
  - docker
before_install:
  - echo "Testing Docker Hub Credentials"
  - docker login -e=$docker_email -u=$docker_user -p=$docker_password
  - echo "Docker Hub credentials are working"
install:
  - docker build -t crosstag .
  - docker run -d -p 0.0.0.0:80:80 crosstag
before_script:
  - pip3 install -r requirements.txt
script:
  - python3 tests/crosstag_api_tests.py
after_success:
  - export database_server=$database_server database_name=$database_name database_password=$database_password database_username=$database_username database_tenantpw=$database_tenantpw
  - echo "Test Success - Branch($TRAVIS_BRANCH) Pull Request($TRAVIS_PULL_REQUEST) Tag($TRAVIS_TAG)"
  - if [[ "$TRAVIS_BRANCH" == "master" ]]; then echo -e "Push Container to Docker Hub"; fi
  - docker login -e=$docker_email -u=$docker_user -p=$docker_password
  - export REPO=crosstag/crosstag
  - export TAG=if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi
  - docker build -f Dockerfile -t $REPO:$COMMIT .
  - docker tag $REPO:$COMMIT $REPO:$TAG
  - docker tag $REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
  - docker push $REPO